import {
  AlignmentType,
  Document,
  HeadingLevel,
  ImageRun,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType
} from "docx";

const HEADING_LEVELS = { 1: HeadingLevel.HEADING_1, 2: HeadingLevel.HEADING_2, 3: HeadingLevel.HEADING_3, 4: HeadingLevel.HEADING_4, 5: HeadingLevel.HEADING_5, 6: HeadingLevel.HEADING_6 };

export async function generateDocx(spec, { resolveAsset } = {}) {
  const warnings = [];
  const children = [];
  for (const block of Array.isArray(spec.content) ? spec.content : []) {
    const result = await blockToDocx(block, { resolveAsset, warnings });
    if (Array.isArray(result)) children.push(...result); else if (result) children.push(result);
  }
  if (!children.length) children.push(new Paragraph({ children: [new TextRun("")] }));
  const document = new Document({
    creator: "WebClaw",
    title: String(spec.document?.title || "WebClaw document"),
    description: String(spec.document?.subject || "Generated by WebClaw"),
    styles: { default: { document: { run: { font: spec.theme?.fonts?.body || "Aptos", size: 22 } } } },
    sections: [{ children }]
  });
  return { blob: await Packer.toBlob(document), warnings, fidelity: warnings.length ? "partial" : "rich" };
}

async function blockToDocx(block, context) {
  const type = String(block?.type || "paragraph").toLowerCase();
  if (type === "heading") return new Paragraph({ heading: HEADING_LEVELS[Math.min(6, Math.max(1, Number(block.level) || 1))], alignment: paragraphAlignment(block.align), children: inlineRuns(block.text, block) });
  if (type === "paragraph" || type === "quote") return new Paragraph({ style: type === "quote" ? "IntenseQuote" : undefined, alignment: paragraphAlignment(block.align), indent: type === "quote" ? { left: 720 } : undefined, children: inlineRuns(block.text ?? block.content, block) });
  if (type === "list") return (Array.isArray(block.items) ? block.items : []).map((item) => new Paragraph({ text: typeof item === "object" ? String(item.text ?? item.content ?? "") : String(item), bullet: { level: Number(block.level) || 0 } }));
  if (type === "table") return tableBlock(block.table || block, context);
  if (type === "page_break") return new Paragraph({ pageBreakBefore: true });
  if (type === "image") {
    if (typeof context.resolveAsset !== "function") {
      context.warnings.push(`Image asset was skipped because no VFS asset resolver was provided: ${block.path || "unknown"}`);
      return new Paragraph({ children: inlineRuns(block.alt || "[image]", {}) });
    }
    const asset = await context.resolveAsset(block.path);
    if (!asset?.data) {
      context.warnings.push(`Image asset was skipped because it could not be read: ${block.path || "unknown"}`);
      return new Paragraph({ children: inlineRuns(block.alt || "[image]", {}) });
    }
    return new Paragraph({ children: [new ImageRun({ data: asset.data, transformation: { width: Number(block.width) || 640, height: Number(block.height) || 360 }, type: asset.mimeType?.split("/")[1] || "png" })] });
  }
  context.warnings.push(`Unsupported DOCX rich block was skipped: ${type}`);
  return new Paragraph({ children: inlineRuns(String(block.text || ""), {}) });
}

function tableBlock(table, context) {
  const columns = Array.isArray(table.columns) ? table.columns : [];
  const rows = Array.isArray(table.rows) ? table.rows : [];
  const keys = columns.length ? columns.map((column) => String(column.key)) : inferKeys(rows);
  const header = columns.length ? keys.map((key, index) => columns[index]?.label || key) : keys;
  const allRows = header.length ? [header, ...rows.map((row) => keys.map((key) => row?.[key] ?? ""))] : rows;
  if (!allRows.length) { context.warnings.push("Empty DOCX table was skipped."); return new Paragraph({ children: inlineRuns("", {}) }); }
  return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: allRows.map((row, rowIndex) => new TableRow({ children: row.map((value) => new TableCell({ shading: rowIndex === 0 && header.length ? { type: ShadingType.CLEAR, fill: "D9EAF7" } : undefined, children: [new Paragraph({ children: inlineRuns(value, {}) })] })) })) });
}

function inlineRuns(value, options = {}) { return [new TextRun({ text: String(value ?? ""), bold: Boolean(options.bold), italics: Boolean(options.italic), color: options.color ? String(options.color).replace(/^#/, "") : undefined })]; }
function paragraphAlignment(value) { const align = String(value || "").toLowerCase(); return align === "center" ? AlignmentType.CENTER : align === "right" ? AlignmentType.RIGHT : align === "justify" ? AlignmentType.JUSTIFIED : AlignmentType.LEFT; }
function inferKeys(rows) { return [...new Set(rows.flatMap((row) => row && typeof row === "object" && !Array.isArray(row) ? Object.keys(row) : []))]; }
